import Database from 'better-sqlite3';
import path from 'path';

const dbPath = path.resolve('server/data/trafficeye.db');
const db = new Database(dbPath);

console.log('Connected to database:', dbPath);

// 1. Ensure all 5 cameras are online and have exact video_file source
const cameras = [
  { id: 'CAM-GATE-01', name: "PVG's College Entrance Node", location: "In front of PVG's College of Engineering, Shiv Darshan Road, Parvati", url: '/videos/pvg_college.mp4', lat: 18.4902, lng: 73.8525 },
  { id: 'CAM 01', name: 'Shiv Darshan Chowk', location: 'Shiv Darshan Chowk', url: '/videos/shiv_darshan_chowk.mp4', lat: 18.4941, lng: 73.8540 },
  { id: 'CAM 03', name: 'Gajanan Maharaj Temple', location: 'Gajanan Maharaj Temple', url: '/videos/gajanan_maharaj_temple.mp4', lat: 18.4975, lng: 73.8572 },
  { id: 'CAM 04', name: 'Aranyeshwar Circle', location: 'Aranyeshwar Circle', url: '/videos/aranyeshwar_circle.mp4', lat: 18.4880, lng: 73.8580 },
  { id: 'CAM 05', name: 'Taware Colony', location: 'Taware Colony', url: '/videos/taware_colony.mp4', lat: 18.4855, lng: 73.8610 }
];

const updateCam = db.prepare(`
  UPDATE cameras 
  SET source_type = 'video_file', source_url = ?, status = 'online', updated_at = datetime('now')
  WHERE id = ?
`);

for (const c of cameras) {
  const res = updateCam.run(c.url, c.id);
  console.log(`Updated camera ${c.id}: ${res.changes} change(s)`);
}

// 2. Remove blacklisted vehicles (dummy data)
const delBL = db.prepare('DELETE FROM blacklist').run();
console.log(`Cleared blacklist dummy records: ${delBL.changes}`);

// 3. Remove dummy alerts generated by blacklist
const delAlerts = db.prepare('DELETE FROM alerts').run();
console.log(`Cleared dummy alerts: ${delAlerts.changes}`);

// 4. Remove dummy detections of blacklisted plates
const delDet = db.prepare(`DELETE FROM detections WHERE plate_number LIKE '%WANTED%' OR plate_number = 'HR35M2576' OR status = 'Flagged'`).run();
console.log(`Cleared dummy detections: ${delDet.changes}`);

console.log('\n--- VERIFICATION ---');
console.log('Cameras:', db.prepare('SELECT id, name, source_url, status FROM cameras').all());
console.log('Remaining blacklist count:', db.prepare('SELECT COUNT(*) as count FROM blacklist').get().count);
console.log('Remaining alerts count:', db.prepare('SELECT COUNT(*) as count FROM alerts').get().count);
console.log('Remaining flagged detections:', db.prepare("SELECT COUNT(*) as count FROM detections WHERE status = 'Flagged'").get().count);
console.log('Remaining total detections:', db.prepare('SELECT COUNT(*) as count FROM detections').get().count);
